// This file was generated by Mendix Business Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package objectbackuprestore.actions;

import objectbackuprestore.BackupObjectImpl;
import objectbackuprestore.proxies.constants.Constants;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Backup an object
 */
public class BackupObjectAction extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __backupRequest;
	private objectbackuprestore.proxies.BackupRequest backupRequest;

	public BackupObjectAction(IContext context, IMendixObject backupRequest)
	{
		super(context);
		this.__backupRequest = backupRequest;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.backupRequest = __backupRequest == null ? null : objectbackuprestore.proxies.BackupRequest.initialize(getContext(), __backupRequest);

		// BEGIN USER CODE
		BackupObjectImpl backupObjectImpl = new BackupObjectImpl(Constants.getOBJECT_BACKUP_RESTORE_LOG_NODE(), getContext());
		return backupObjectImpl.runBackup(backupRequest);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "BackupObjectAction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
