// This file was generated by Mendix Business Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package objectbackuprestore.actions;

import objectbackuprestore.RestoreObjectsImpl;
import objectbackuprestore.proxies.constants.Constants;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Restore objects from a backup
 */
public class RestoreObjectsAction extends CustomJavaAction<Boolean>
{
	private IMendixObject __backup;
	private objectbackuprestore.proxies.Backup backup;
	private IMendixObject __restoreRequest;
	private objectbackuprestore.proxies.RestoreRequest restoreRequest;
	private objectbackuprestore.proxies.RestoreActionType actionType;

	public RestoreObjectsAction(IContext context, IMendixObject backup, IMendixObject restoreRequest, String actionType)
	{
		super(context);
		this.__backup = backup;
		this.__restoreRequest = restoreRequest;
		this.actionType = actionType == null ? null : objectbackuprestore.proxies.RestoreActionType.valueOf(actionType);
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		this.backup = __backup == null ? null : objectbackuprestore.proxies.Backup.initialize(getContext(), __backup);

		this.restoreRequest = __restoreRequest == null ? null : objectbackuprestore.proxies.RestoreRequest.initialize(getContext(), __restoreRequest);

		// BEGIN USER CODE
		RestoreObjectsImpl backupRestoreObjectsImpl = new RestoreObjectsImpl(Constants.getOBJECT_BACKUP_RESTORE_LOG_NODE(), getContext());
		return backupRestoreObjectsImpl.restoreObjects(backup, restoreRequest, actionType);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "RestoreObjectsAction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
