// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package objectbackuprestore.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the Microflows for the ObjectBackupRestore module

	public static objectbackuprestore.proxies.BackupConfigurationTreeData dS_BackupConfigurationTree(IContext context, objectbackuprestore.proxies.BackupConfiguration _backupConfiguration)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("backupConfiguration", _backupConfiguration == null ? null : _backupConfiguration.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "ObjectBackupRestore.DS_BackupConfigurationTree", params);
			return result == null ? null : objectbackuprestore.proxies.BackupConfigurationTreeData.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static objectbackuprestore.proxies.ObjectType dS_GetObjectTypeForConfigurationEntity(IContext context, objectbackuprestore.proxies.BackupConfiguration _backupConfiguration)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("backupConfiguration", _backupConfiguration == null ? null : _backupConfiguration.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "ObjectBackupRestore.DS_GetObjectTypeForConfigurationEntity", params);
			return result == null ? null : objectbackuprestore.proxies.ObjectType.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_Backup_FilterObjects(IContext context, objectbackuprestore.proxies.RestoreRequest _restoreRequest)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("restoreRequest", _restoreRequest == null ? null : _restoreRequest.getMendixObject());
			Core.execute(context, "ObjectBackupRestore.IVK_Backup_FilterObjects", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_Backup_Import(IContext context, objectbackuprestore.proxies.Backup _backup)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("backup", _backup == null ? null : _backup.getMendixObject());
			Core.execute(context, "ObjectBackupRestore.IVK_Backup_Import", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_Backup_Import_Start(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "ObjectBackupRestore.IVK_Backup_Import_Start", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_Backup_LoadObjects(IContext context, objectbackuprestore.proxies.Backup _backup)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("backup", _backup == null ? null : _backup.getMendixObject());
			Core.execute(context, "ObjectBackupRestore.IVK_Backup_LoadObjects", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_Backup_RestoreObjects(IContext context, objectbackuprestore.proxies.RestoreRequest _restoreRequest)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("restoreRequest", _restoreRequest == null ? null : _restoreRequest.getMendixObject());
			Core.execute(context, "ObjectBackupRestore.IVK_Backup_RestoreObjects", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_Backup_ShowObjects(IContext context, objectbackuprestore.proxies.RestoreRequest _restoreRequest)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("restoreRequest", _restoreRequest == null ? null : _restoreRequest.getMendixObject());
			Core.execute(context, "ObjectBackupRestore.IVK_Backup_ShowObjects", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_BackupConfiguration_Edit(IContext context, objectbackuprestore.proxies.BackupConfiguration _backupConfiguration)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("backupConfiguration", _backupConfiguration == null ? null : _backupConfiguration.getMendixObject());
			Core.execute(context, "ObjectBackupRestore.IVK_BackupConfiguration_Edit", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_BackupConfiguration_EditObjectType(IContext context, objectbackuprestore.proxies.BackupConfiguration _backupConfiguration)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("backupConfiguration", _backupConfiguration == null ? null : _backupConfiguration.getMendixObject());
			Core.execute(context, "ObjectBackupRestore.IVK_BackupConfiguration_EditObjectType", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_BackupConfiguration_SaveNew(IContext context, objectbackuprestore.proxies.BackupConfiguration _backupConfiguration)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("backupConfiguration", _backupConfiguration == null ? null : _backupConfiguration.getMendixObject());
			Core.execute(context, "ObjectBackupRestore.IVK_BackupConfiguration_SaveNew", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_BackupConfigurationObject_EditObjectType(IContext context, objectbackuprestore.proxies.BackupConfigurationObject _backupConfigurationObject)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("backupConfigurationObject", _backupConfigurationObject == null ? null : _backupConfigurationObject.getMendixObject());
			Core.execute(context, "ObjectBackupRestore.IVK_BackupConfigurationObject_EditObjectType", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_BackupConfigurationObject_SetNextLevelUnknownToNo(IContext context, objectbackuprestore.proxies.BackupConfigurationTreeData _treeData, objectbackuprestore.proxies.BackupConfigurationReferenceNodeData _nodeData)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("treeData", _treeData == null ? null : _treeData.getMendixObject());
			params.put("nodeData", _nodeData == null ? null : _nodeData.getMendixObject());
			Core.execute(context, "ObjectBackupRestore.IVK_BackupConfigurationObject_SetNextLevelUnknownToNo", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_BackupConfigurationObject_ToggleInclude(IContext context, objectbackuprestore.proxies.BackupConfigurationObject _backupConfigurationObject, objectbackuprestore.proxies.BackupConfigurationReferenceNodeData _nodeData)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("backupConfigurationObject", _backupConfigurationObject == null ? null : _backupConfigurationObject.getMendixObject());
			params.put("nodeData", _nodeData == null ? null : _nodeData.getMendixObject());
			Core.execute(context, "ObjectBackupRestore.IVK_BackupConfigurationObject_ToggleInclude", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_BackupRequest_Copy(IContext context, objectbackuprestore.proxies.BackupRequest _backupRequest)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("backupRequest", _backupRequest == null ? null : _backupRequest.getMendixObject());
			Core.execute(context, "ObjectBackupRestore.IVK_BackupRequest_Copy", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_ObjectType_ShowOverview(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "ObjectBackupRestore.IVK_ObjectType_ShowOverview", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_ObjectType_StartEdit(IContext context, objectbackuprestore.proxies.ObjectType _objectType)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("objectType", _objectType == null ? null : _objectType.getMendixObject());
			Core.execute(context, "ObjectBackupRestore.IVK_ObjectType_StartEdit", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_RunBackup(IContext context, objectbackuprestore.proxies.BackupRequest _backupRequest)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("backupRequest", _backupRequest == null ? null : _backupRequest.getMendixObject());
			Core.execute(context, "ObjectBackupRestore.IVK_RunBackup", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static java.util.List<objectbackuprestore.proxies.BackupConfigurationTreeNodeData> jS_BackupConfigurationTree_GetData(IContext context, objectbackuprestore.proxies.BackupConfigurationTreeData _treeData)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("treeData", _treeData == null ? null : _treeData.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "ObjectBackupRestore.JS_BackupConfigurationTree_GetData", params);
			java.util.List<objectbackuprestore.proxies.BackupConfigurationTreeNodeData> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<objectbackuprestore.proxies.BackupConfigurationTreeNodeData>();
				for (IMendixObject obj : objs)
					result.add(objectbackuprestore.proxies.BackupConfigurationTreeNodeData.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void jS_BackupConfigurationTree_OnClick(IContext context, objectbackuprestore.proxies.BackupConfigurationTreeNodeData _nodeData)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("nodeData", _nodeData == null ? null : _nodeData.getMendixObject());
			Core.execute(context, "ObjectBackupRestore.JS_BackupConfigurationTree_OnClick", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void oCh_BackupConfiguration_Object(IContext context, objectbackuprestore.proxies.BackupConfiguration _backupConfiguration)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("backupConfiguration", _backupConfiguration == null ? null : _backupConfiguration.getMendixObject());
			Core.execute(context, "ObjectBackupRestore.OCh_BackupConfiguration_Object", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void oCh_BackupRequest_BackupConfiguration_XPathConstraint(IContext context, objectbackuprestore.proxies.BackupRequest _backupRequest)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("backupRequest", _backupRequest == null ? null : _backupRequest.getMendixObject());
			Core.execute(context, "ObjectBackupRestore.OCh_BackupRequest_BackupConfiguration_XPathConstraint", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void sE_CheckBackupConfigurations(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "ObjectBackupRestore.SE_CheckBackupConfigurations", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void sUB_BackupConfiguration_ConfigurationCleanup(IContext context, objectbackuprestore.proxies.BackupConfiguration _backupConfiguration)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("backupConfiguration", _backupConfiguration == null ? null : _backupConfiguration.getMendixObject());
			Core.execute(context, "ObjectBackupRestore.SUB_BackupConfiguration_ConfigurationCleanup", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static objectbackuprestore.proxies.BackupConfigurationObject sUB_BackupConfigurationObject_GetOrCreate(IContext context, objectbackuprestore.proxies.BackupConfigurationObject _parentObject, mxmodelreflection.proxies.MxObjectType _entity, objectbackuprestore.proxies.BackupConfiguration _backupConfiguration, mxmodelreflection.proxies.MxObjectReference _reference, objectbackuprestore.proxies.ReferenceType _referenceType)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("parentObject", _parentObject == null ? null : _parentObject.getMendixObject());
			params.put("entity", _entity == null ? null : _entity.getMendixObject());
			params.put("backupConfiguration", _backupConfiguration == null ? null : _backupConfiguration.getMendixObject());
			params.put("reference", _reference == null ? null : _reference.getMendixObject());
			params.put("referenceType", _referenceType == null ? null : _referenceType.name());
			IMendixObject result = (IMendixObject)Core.execute(context, "ObjectBackupRestore.SUB_BackupConfigurationObject_GetOrCreate", params);
			return result == null ? null : objectbackuprestore.proxies.BackupConfigurationObject.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void sUB_BackupConfigurationTree_BuildEntityNode(IContext context, objectbackuprestore.proxies.BackupConfiguration _backupConfiguration, java.util.List<objectbackuprestore.proxies.BackupConfigurationTreeNodeData> _nodeList, mxmodelreflection.proxies.MxObjectType _entity, objectbackuprestore.proxies.BackupConfigurationTreeData _treeData, objectbackuprestore.proxies.BackupConfigurationObject _parentObject, objectbackuprestore.proxies.BackupConfigurationReferenceNodeData _parentNode)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("backupConfiguration", _backupConfiguration == null ? null : _backupConfiguration.getMendixObject());
			java.util.ArrayList<IMendixObject> listparam_nodeList = null;
			if (_nodeList != null)
			{
				listparam_nodeList = new java.util.ArrayList<IMendixObject>();
				for (objectbackuprestore.proxies.BackupConfigurationTreeNodeData obj : _nodeList)
					listparam_nodeList.add(obj.getMendixObject());
			}
			params.put("nodeList", listparam_nodeList);
			params.put("entity", _entity == null ? null : _entity.getMendixObject());
			params.put("treeData", _treeData == null ? null : _treeData.getMendixObject());
			params.put("parentObject", _parentObject == null ? null : _parentObject.getMendixObject());
			params.put("parentNode", _parentNode == null ? null : _parentNode.getMendixObject());
			Core.execute(context, "ObjectBackupRestore.SUB_BackupConfigurationTree_BuildEntityNode", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void sUB_BackupConfigurationTree_CreateReferenceNode(IContext context, objectbackuprestore.proxies.BackupConfiguration _backupConfiguration, java.util.List<objectbackuprestore.proxies.BackupConfigurationTreeNodeData> _nodeList, objectbackuprestore.proxies.BackupConfigurationTreeData _treeData, objectbackuprestore.proxies.BackupConfigurationObject _parentObject, mxmodelreflection.proxies.MxObjectReference _reference, objectbackuprestore.proxies.BackupConfigurationEntityNodeData _entityNode, java.util.List<mxmodelreflection.proxies.MxObjectType> _referencedEntityList, mxmodelreflection.proxies.MxObjectType _entity, boolean _isReverseReference)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("backupConfiguration", _backupConfiguration == null ? null : _backupConfiguration.getMendixObject());
			java.util.ArrayList<IMendixObject> listparam_nodeList = null;
			if (_nodeList != null)
			{
				listparam_nodeList = new java.util.ArrayList<IMendixObject>();
				for (objectbackuprestore.proxies.BackupConfigurationTreeNodeData obj : _nodeList)
					listparam_nodeList.add(obj.getMendixObject());
			}
			params.put("nodeList", listparam_nodeList);
			params.put("treeData", _treeData == null ? null : _treeData.getMendixObject());
			params.put("parentObject", _parentObject == null ? null : _parentObject.getMendixObject());
			params.put("reference", _reference == null ? null : _reference.getMendixObject());
			params.put("entityNode", _entityNode == null ? null : _entityNode.getMendixObject());
			java.util.ArrayList<IMendixObject> listparam_referencedEntityList = null;
			if (_referencedEntityList != null)
			{
				listparam_referencedEntityList = new java.util.ArrayList<IMendixObject>();
				for (mxmodelreflection.proxies.MxObjectType obj : _referencedEntityList)
					listparam_referencedEntityList.add(obj.getMendixObject());
			}
			params.put("referencedEntityList", listparam_referencedEntityList);
			params.put("entity", _entity == null ? null : _entity.getMendixObject());
			params.put("isReverseReference", _isReverseReference);
			Core.execute(context, "ObjectBackupRestore.SUB_BackupConfigurationTree_CreateReferenceNode", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static java.util.List<objectbackuprestore.proxies.BackupConfigurationTreeNodeData> sUB_BackupConfigurationTree_GetData_EntityNode(IContext context, objectbackuprestore.proxies.BackupConfigurationTreeData _treeData)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("treeData", _treeData == null ? null : _treeData.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "ObjectBackupRestore.SUB_BackupConfigurationTree_GetData_EntityNode", params);
			java.util.List<objectbackuprestore.proxies.BackupConfigurationTreeNodeData> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<objectbackuprestore.proxies.BackupConfigurationTreeNodeData>();
				for (IMendixObject obj : objs)
					result.add(objectbackuprestore.proxies.BackupConfigurationTreeNodeData.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static java.util.List<objectbackuprestore.proxies.BackupConfigurationTreeNodeData> sUB_BackupConfigurationTree_GetData_Full(IContext context, objectbackuprestore.proxies.BackupConfigurationTreeData _treeData)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("treeData", _treeData == null ? null : _treeData.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "ObjectBackupRestore.SUB_BackupConfigurationTree_GetData_Full", params);
			java.util.List<objectbackuprestore.proxies.BackupConfigurationTreeNodeData> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<objectbackuprestore.proxies.BackupConfigurationTreeNodeData>();
				for (IMendixObject obj : objs)
					result.add(objectbackuprestore.proxies.BackupConfigurationTreeNodeData.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void sUB_BackupConfigurationTree_SetReferenceNodeClass(IContext context, objectbackuprestore.proxies.BackupConfigurationReferenceNodeData _referenceNode, objectbackuprestore.proxies.BackupConfigurationObject _backupConfigurationObject)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("referenceNode", _referenceNode == null ? null : _referenceNode.getMendixObject());
			params.put("backupConfigurationObject", _backupConfigurationObject == null ? null : _backupConfigurationObject.getMendixObject());
			Core.execute(context, "ObjectBackupRestore.SUB_BackupConfigurationTree_SetReferenceNodeClass", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static boolean sUB_CheckBackupConfiguration(IContext context, objectbackuprestore.proxies.BackupConfiguration _backupConfiguration)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("backupConfiguration", _backupConfiguration == null ? null : _backupConfiguration.getMendixObject());
			return (Boolean)Core.execute(context, "ObjectBackupRestore.SUB_CheckBackupConfiguration", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static objectbackuprestore.proxies.ObjectType sUB_ObjectType_GetOrCreate(IContext context, mxmodelreflection.proxies.MxObjectType _entity)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("entity", _entity == null ? null : _entity.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "ObjectBackupRestore.SUB_ObjectType_GetOrCreate", params);
			return result == null ? null : objectbackuprestore.proxies.ObjectType.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}