// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package objectbackuprestore.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class BackupConfigurationObject
{
	private final IMendixObject backupConfigurationObjectMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "ObjectBackupRestore.BackupConfigurationObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Path("Path"),
		ReferenceName("ReferenceName"),
		ModuleName("ModuleName"),
		CompleteReferenceName("CompleteReferenceName"),
		IncludeInBackup("IncludeInBackup"),
		ReferenceType("ReferenceType"),
		ReferencedEntityCompleteName("ReferencedEntityCompleteName"),
		BackupConfigurationObject_BackupConfiguration("ObjectBackupRestore.BackupConfigurationObject_BackupConfiguration"),
		BackupConfigurationObject_ObjectType("ObjectBackupRestore.BackupConfigurationObject_ObjectType"),
		ParentConfigurationObject("ObjectBackupRestore.ParentConfigurationObject");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public BackupConfigurationObject(IContext context)
	{
		this(context, Core.instantiate(context, "ObjectBackupRestore.BackupConfigurationObject"));
	}

	protected BackupConfigurationObject(IContext context, IMendixObject backupConfigurationObjectMendixObject)
	{
		if (backupConfigurationObjectMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("ObjectBackupRestore.BackupConfigurationObject", backupConfigurationObjectMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a ObjectBackupRestore.BackupConfigurationObject");

		this.backupConfigurationObjectMendixObject = backupConfigurationObjectMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'new BackupConfigurationObject(Context)' instead. Note that the constructor will not insert the new object in the database.
	 */
	@Deprecated
	public static objectbackuprestore.proxies.BackupConfigurationObject create(IContext context) throws CoreException
	{
		IMendixObject mendixObject = Core.create(context, "ObjectBackupRestore.BackupConfigurationObject");
		return new objectbackuprestore.proxies.BackupConfigurationObject(context, mendixObject);
	}

	/**
	 * @deprecated Use 'BackupConfigurationObject.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static objectbackuprestore.proxies.BackupConfigurationObject initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return objectbackuprestore.proxies.BackupConfigurationObject.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static objectbackuprestore.proxies.BackupConfigurationObject initialize(IContext context, IMendixObject mendixObject)
	{
		return new objectbackuprestore.proxies.BackupConfigurationObject(context, mendixObject);
	}

	public static objectbackuprestore.proxies.BackupConfigurationObject load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return objectbackuprestore.proxies.BackupConfigurationObject.initialize(context, mendixObject);
	}

	public static java.util.List<objectbackuprestore.proxies.BackupConfigurationObject> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<objectbackuprestore.proxies.BackupConfigurationObject> result = new java.util.ArrayList<objectbackuprestore.proxies.BackupConfigurationObject>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//ObjectBackupRestore.BackupConfigurationObject" + xpathConstraint))
			result.add(objectbackuprestore.proxies.BackupConfigurationObject.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Path
	 */
	public final String getPath()
	{
		return getPath(getContext());
	}

	/**
	 * @param context
	 * @return value of Path
	 */
	public final String getPath(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Path.toString());
	}

	/**
	 * Set value of Path
	 * @param path
	 */
	public final void setPath(String path)
	{
		setPath(getContext(), path);
	}

	/**
	 * Set value of Path
	 * @param context
	 * @param path
	 */
	public final void setPath(IContext context, String path)
	{
		getMendixObject().setValue(context, MemberNames.Path.toString(), path);
	}

	/**
	 * @return value of ReferenceName
	 */
	public final String getReferenceName()
	{
		return getReferenceName(getContext());
	}

	/**
	 * @param context
	 * @return value of ReferenceName
	 */
	public final String getReferenceName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ReferenceName.toString());
	}

	/**
	 * Set value of ReferenceName
	 * @param referencename
	 */
	public final void setReferenceName(String referencename)
	{
		setReferenceName(getContext(), referencename);
	}

	/**
	 * Set value of ReferenceName
	 * @param context
	 * @param referencename
	 */
	public final void setReferenceName(IContext context, String referencename)
	{
		getMendixObject().setValue(context, MemberNames.ReferenceName.toString(), referencename);
	}

	/**
	 * @return value of ModuleName
	 */
	public final String getModuleName()
	{
		return getModuleName(getContext());
	}

	/**
	 * @param context
	 * @return value of ModuleName
	 */
	public final String getModuleName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ModuleName.toString());
	}

	/**
	 * Set value of ModuleName
	 * @param modulename
	 */
	public final void setModuleName(String modulename)
	{
		setModuleName(getContext(), modulename);
	}

	/**
	 * Set value of ModuleName
	 * @param context
	 * @param modulename
	 */
	public final void setModuleName(IContext context, String modulename)
	{
		getMendixObject().setValue(context, MemberNames.ModuleName.toString(), modulename);
	}

	/**
	 * @return value of CompleteReferenceName
	 */
	public final String getCompleteReferenceName()
	{
		return getCompleteReferenceName(getContext());
	}

	/**
	 * @param context
	 * @return value of CompleteReferenceName
	 */
	public final String getCompleteReferenceName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.CompleteReferenceName.toString());
	}

	/**
	 * Set value of CompleteReferenceName
	 * @param completereferencename
	 */
	public final void setCompleteReferenceName(String completereferencename)
	{
		setCompleteReferenceName(getContext(), completereferencename);
	}

	/**
	 * Set value of CompleteReferenceName
	 * @param context
	 * @param completereferencename
	 */
	public final void setCompleteReferenceName(IContext context, String completereferencename)
	{
		getMendixObject().setValue(context, MemberNames.CompleteReferenceName.toString(), completereferencename);
	}

	/**
	 * Set value of IncludeInBackup
	 * @param includeinbackup
	 */
	public final objectbackuprestore.proxies.IncludeInBackup getIncludeInBackup()
	{
		return getIncludeInBackup(getContext());
	}

	/**
	 * @param context
	 * @return value of IncludeInBackup
	 */
	public final objectbackuprestore.proxies.IncludeInBackup getIncludeInBackup(IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.IncludeInBackup.toString());
		if (obj == null)
			return null;

		return objectbackuprestore.proxies.IncludeInBackup.valueOf((String) obj);
	}

	/**
	 * Set value of IncludeInBackup
	 * @param includeinbackup
	 */
	public final void setIncludeInBackup(objectbackuprestore.proxies.IncludeInBackup includeinbackup)
	{
		setIncludeInBackup(getContext(), includeinbackup);
	}

	/**
	 * Set value of IncludeInBackup
	 * @param context
	 * @param includeinbackup
	 */
	public final void setIncludeInBackup(IContext context, objectbackuprestore.proxies.IncludeInBackup includeinbackup)
	{
		if (includeinbackup != null)
			getMendixObject().setValue(context, MemberNames.IncludeInBackup.toString(), includeinbackup.toString());
		else
			getMendixObject().setValue(context, MemberNames.IncludeInBackup.toString(), null);
	}

	/**
	 * Set value of ReferenceType
	 * @param referencetype
	 */
	public final objectbackuprestore.proxies.ReferenceType getReferenceType()
	{
		return getReferenceType(getContext());
	}

	/**
	 * @param context
	 * @return value of ReferenceType
	 */
	public final objectbackuprestore.proxies.ReferenceType getReferenceType(IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ReferenceType.toString());
		if (obj == null)
			return null;

		return objectbackuprestore.proxies.ReferenceType.valueOf((String) obj);
	}

	/**
	 * Set value of ReferenceType
	 * @param referencetype
	 */
	public final void setReferenceType(objectbackuprestore.proxies.ReferenceType referencetype)
	{
		setReferenceType(getContext(), referencetype);
	}

	/**
	 * Set value of ReferenceType
	 * @param context
	 * @param referencetype
	 */
	public final void setReferenceType(IContext context, objectbackuprestore.proxies.ReferenceType referencetype)
	{
		if (referencetype != null)
			getMendixObject().setValue(context, MemberNames.ReferenceType.toString(), referencetype.toString());
		else
			getMendixObject().setValue(context, MemberNames.ReferenceType.toString(), null);
	}

	/**
	 * @return value of ReferencedEntityCompleteName
	 */
	public final String getReferencedEntityCompleteName()
	{
		return getReferencedEntityCompleteName(getContext());
	}

	/**
	 * @param context
	 * @return value of ReferencedEntityCompleteName
	 */
	public final String getReferencedEntityCompleteName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ReferencedEntityCompleteName.toString());
	}

	/**
	 * Set value of ReferencedEntityCompleteName
	 * @param referencedentitycompletename
	 */
	public final void setReferencedEntityCompleteName(String referencedentitycompletename)
	{
		setReferencedEntityCompleteName(getContext(), referencedentitycompletename);
	}

	/**
	 * Set value of ReferencedEntityCompleteName
	 * @param context
	 * @param referencedentitycompletename
	 */
	public final void setReferencedEntityCompleteName(IContext context, String referencedentitycompletename)
	{
		getMendixObject().setValue(context, MemberNames.ReferencedEntityCompleteName.toString(), referencedentitycompletename);
	}

	/**
	 * @return value of BackupConfigurationObject_BackupConfiguration
	 */
	public final objectbackuprestore.proxies.BackupConfiguration getBackupConfigurationObject_BackupConfiguration() throws CoreException
	{
		return getBackupConfigurationObject_BackupConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of BackupConfigurationObject_BackupConfiguration
	 */
	public final objectbackuprestore.proxies.BackupConfiguration getBackupConfigurationObject_BackupConfiguration(IContext context) throws CoreException
	{
		objectbackuprestore.proxies.BackupConfiguration result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BackupConfigurationObject_BackupConfiguration.toString());
		if (identifier != null)
			result = objectbackuprestore.proxies.BackupConfiguration.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BackupConfigurationObject_BackupConfiguration
	 * @param backupconfigurationobject_backupconfiguration
	 */
	public final void setBackupConfigurationObject_BackupConfiguration(objectbackuprestore.proxies.BackupConfiguration backupconfigurationobject_backupconfiguration)
	{
		setBackupConfigurationObject_BackupConfiguration(getContext(), backupconfigurationobject_backupconfiguration);
	}

	/**
	 * Set value of BackupConfigurationObject_BackupConfiguration
	 * @param context
	 * @param backupconfigurationobject_backupconfiguration
	 */
	public final void setBackupConfigurationObject_BackupConfiguration(IContext context, objectbackuprestore.proxies.BackupConfiguration backupconfigurationobject_backupconfiguration)
	{
		if (backupconfigurationobject_backupconfiguration == null)
			getMendixObject().setValue(context, MemberNames.BackupConfigurationObject_BackupConfiguration.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BackupConfigurationObject_BackupConfiguration.toString(), backupconfigurationobject_backupconfiguration.getMendixObject().getId());
	}

	/**
	 * @return value of BackupConfigurationObject_ObjectType
	 */
	public final objectbackuprestore.proxies.ObjectType getBackupConfigurationObject_ObjectType() throws CoreException
	{
		return getBackupConfigurationObject_ObjectType(getContext());
	}

	/**
	 * @param context
	 * @return value of BackupConfigurationObject_ObjectType
	 */
	public final objectbackuprestore.proxies.ObjectType getBackupConfigurationObject_ObjectType(IContext context) throws CoreException
	{
		objectbackuprestore.proxies.ObjectType result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BackupConfigurationObject_ObjectType.toString());
		if (identifier != null)
			result = objectbackuprestore.proxies.ObjectType.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BackupConfigurationObject_ObjectType
	 * @param backupconfigurationobject_objecttype
	 */
	public final void setBackupConfigurationObject_ObjectType(objectbackuprestore.proxies.ObjectType backupconfigurationobject_objecttype)
	{
		setBackupConfigurationObject_ObjectType(getContext(), backupconfigurationobject_objecttype);
	}

	/**
	 * Set value of BackupConfigurationObject_ObjectType
	 * @param context
	 * @param backupconfigurationobject_objecttype
	 */
	public final void setBackupConfigurationObject_ObjectType(IContext context, objectbackuprestore.proxies.ObjectType backupconfigurationobject_objecttype)
	{
		if (backupconfigurationobject_objecttype == null)
			getMendixObject().setValue(context, MemberNames.BackupConfigurationObject_ObjectType.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BackupConfigurationObject_ObjectType.toString(), backupconfigurationobject_objecttype.getMendixObject().getId());
	}

	/**
	 * @return value of ParentConfigurationObject
	 */
	public final objectbackuprestore.proxies.BackupConfigurationObject getParentConfigurationObject() throws CoreException
	{
		return getParentConfigurationObject(getContext());
	}

	/**
	 * @param context
	 * @return value of ParentConfigurationObject
	 */
	public final objectbackuprestore.proxies.BackupConfigurationObject getParentConfigurationObject(IContext context) throws CoreException
	{
		objectbackuprestore.proxies.BackupConfigurationObject result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ParentConfigurationObject.toString());
		if (identifier != null)
			result = objectbackuprestore.proxies.BackupConfigurationObject.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ParentConfigurationObject
	 * @param parentconfigurationobject
	 */
	public final void setParentConfigurationObject(objectbackuprestore.proxies.BackupConfigurationObject parentconfigurationobject)
	{
		setParentConfigurationObject(getContext(), parentconfigurationobject);
	}

	/**
	 * Set value of ParentConfigurationObject
	 * @param context
	 * @param parentconfigurationobject
	 */
	public final void setParentConfigurationObject(IContext context, objectbackuprestore.proxies.BackupConfigurationObject parentconfigurationobject)
	{
		if (parentconfigurationobject == null)
			getMendixObject().setValue(context, MemberNames.ParentConfigurationObject.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ParentConfigurationObject.toString(), parentconfigurationobject.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return backupConfigurationObjectMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final objectbackuprestore.proxies.BackupConfigurationObject that = (objectbackuprestore.proxies.BackupConfigurationObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "ObjectBackupRestore.BackupConfigurationObject";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
