// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package objectbackuprestore.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class BackupConfigurationTreeNodeData extends objectbackuprestore.proxies.TreeViewNodeData
{
	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "ObjectBackupRestore.BackupConfigurationTreeNodeData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Caption("Caption"),
		NodeClass("NodeClass"),
		Key("Key"),
		BackupConfigurationObjectNodeData_BackupConfigurationTreeData("ObjectBackupRestore.BackupConfigurationObjectNodeData_BackupConfigurationTreeData"),
		TreeViewNodeData_TreeViewWidgetData("ObjectBackupRestore.TreeViewNodeData_TreeViewWidgetData"),
		ParentNode("ObjectBackupRestore.ParentNode");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public BackupConfigurationTreeNodeData(IContext context)
	{
		this(context, Core.instantiate(context, "ObjectBackupRestore.BackupConfigurationTreeNodeData"));
	}

	protected BackupConfigurationTreeNodeData(IContext context, IMendixObject backupConfigurationTreeNodeDataMendixObject)
	{
		super(context, backupConfigurationTreeNodeDataMendixObject);
		if (!Core.isSubClassOf("ObjectBackupRestore.BackupConfigurationTreeNodeData", backupConfigurationTreeNodeDataMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a ObjectBackupRestore.BackupConfigurationTreeNodeData");
	}

	/**
	 * @deprecated Use 'new BackupConfigurationTreeNodeData(Context)' instead. Note that the constructor will not insert the new object in the database.
	 */
	@Deprecated
	public static objectbackuprestore.proxies.BackupConfigurationTreeNodeData create(IContext context) throws CoreException
	{
		IMendixObject mendixObject = Core.create(context, "ObjectBackupRestore.BackupConfigurationTreeNodeData");
		return new objectbackuprestore.proxies.BackupConfigurationTreeNodeData(context, mendixObject);
	}

	/**
	 * @deprecated Use 'BackupConfigurationTreeNodeData.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static objectbackuprestore.proxies.BackupConfigurationTreeNodeData initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return objectbackuprestore.proxies.BackupConfigurationTreeNodeData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static objectbackuprestore.proxies.BackupConfigurationTreeNodeData initialize(IContext context, IMendixObject mendixObject)
	{
		if (Core.isSubClassOf("ObjectBackupRestore.BackupConfigurationEntityNodeData", mendixObject.getType()))
			return objectbackuprestore.proxies.BackupConfigurationEntityNodeData.initialize(context, mendixObject);

		if (Core.isSubClassOf("ObjectBackupRestore.BackupConfigurationReferenceNodeData", mendixObject.getType()))
			return objectbackuprestore.proxies.BackupConfigurationReferenceNodeData.initialize(context, mendixObject);

		return new objectbackuprestore.proxies.BackupConfigurationTreeNodeData(context, mendixObject);
	}

	public static objectbackuprestore.proxies.BackupConfigurationTreeNodeData load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return objectbackuprestore.proxies.BackupConfigurationTreeNodeData.initialize(context, mendixObject);
	}

	/**
	 * @return value of BackupConfigurationObjectNodeData_BackupConfigurationTreeData
	 */
	public final objectbackuprestore.proxies.BackupConfigurationTreeData getBackupConfigurationObjectNodeData_BackupConfigurationTreeData() throws CoreException
	{
		return getBackupConfigurationObjectNodeData_BackupConfigurationTreeData(getContext());
	}

	/**
	 * @param context
	 * @return value of BackupConfigurationObjectNodeData_BackupConfigurationTreeData
	 */
	public final objectbackuprestore.proxies.BackupConfigurationTreeData getBackupConfigurationObjectNodeData_BackupConfigurationTreeData(IContext context) throws CoreException
	{
		objectbackuprestore.proxies.BackupConfigurationTreeData result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BackupConfigurationObjectNodeData_BackupConfigurationTreeData.toString());
		if (identifier != null)
			result = objectbackuprestore.proxies.BackupConfigurationTreeData.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BackupConfigurationObjectNodeData_BackupConfigurationTreeData
	 * @param backupconfigurationobjectnodedata_backupconfigurationtreedata
	 */
	public final void setBackupConfigurationObjectNodeData_BackupConfigurationTreeData(objectbackuprestore.proxies.BackupConfigurationTreeData backupconfigurationobjectnodedata_backupconfigurationtreedata)
	{
		setBackupConfigurationObjectNodeData_BackupConfigurationTreeData(getContext(), backupconfigurationobjectnodedata_backupconfigurationtreedata);
	}

	/**
	 * Set value of BackupConfigurationObjectNodeData_BackupConfigurationTreeData
	 * @param context
	 * @param backupconfigurationobjectnodedata_backupconfigurationtreedata
	 */
	public final void setBackupConfigurationObjectNodeData_BackupConfigurationTreeData(IContext context, objectbackuprestore.proxies.BackupConfigurationTreeData backupconfigurationobjectnodedata_backupconfigurationtreedata)
	{
		if (backupconfigurationobjectnodedata_backupconfigurationtreedata == null)
			getMendixObject().setValue(context, MemberNames.BackupConfigurationObjectNodeData_BackupConfigurationTreeData.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BackupConfigurationObjectNodeData_BackupConfigurationTreeData.toString(), backupconfigurationobjectnodedata_backupconfigurationtreedata.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final objectbackuprestore.proxies.BackupConfigurationTreeNodeData that = (objectbackuprestore.proxies.BackupConfigurationTreeNodeData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "ObjectBackupRestore.BackupConfigurationTreeNodeData";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
