// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package objectbackuprestore.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class Backup extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "ObjectBackupRestore.Backup";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CreationDateTime("CreationDateTime"),
		ObjectCount("ObjectCount"),
		ReferencedObjectCount("ReferencedObjectCount"),
		FileDocumentCount("FileDocumentCount"),
		Checksum("Checksum"),
		GroupCode("GroupCode"),
		Description("Description"),
		Imported("Imported"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Backup_BackupConfiguration("ObjectBackupRestore.Backup_BackupConfiguration"),
		Backup_BackupGroup("ObjectBackupRestore.Backup_BackupGroup");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public Backup(IContext context)
	{
		this(context, Core.instantiate(context, "ObjectBackupRestore.Backup"));
	}

	protected Backup(IContext context, IMendixObject backupMendixObject)
	{
		super(context, backupMendixObject);
		if (!Core.isSubClassOf("ObjectBackupRestore.Backup", backupMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a ObjectBackupRestore.Backup");
	}

	/**
	 * @deprecated Use 'new Backup(Context)' instead. Note that the constructor will not insert the new object in the database.
	 */
	@Deprecated
	public static objectbackuprestore.proxies.Backup create(IContext context) throws CoreException
	{
		IMendixObject mendixObject = Core.create(context, "ObjectBackupRestore.Backup");
		return new objectbackuprestore.proxies.Backup(context, mendixObject);
	}

	/**
	 * @deprecated Use 'Backup.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static objectbackuprestore.proxies.Backup initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return objectbackuprestore.proxies.Backup.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static objectbackuprestore.proxies.Backup initialize(IContext context, IMendixObject mendixObject)
	{
		return new objectbackuprestore.proxies.Backup(context, mendixObject);
	}

	public static objectbackuprestore.proxies.Backup load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return objectbackuprestore.proxies.Backup.initialize(context, mendixObject);
	}

	public static java.util.List<objectbackuprestore.proxies.Backup> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<objectbackuprestore.proxies.Backup> result = new java.util.ArrayList<objectbackuprestore.proxies.Backup>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//ObjectBackupRestore.Backup" + xpathConstraint))
			result.add(objectbackuprestore.proxies.Backup.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of CreationDateTime
	 */
	public final java.util.Date getCreationDateTime()
	{
		return getCreationDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of CreationDateTime
	 */
	public final java.util.Date getCreationDateTime(IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CreationDateTime.toString());
	}

	/**
	 * Set value of CreationDateTime
	 * @param creationdatetime
	 */
	public final void setCreationDateTime(java.util.Date creationdatetime)
	{
		setCreationDateTime(getContext(), creationdatetime);
	}

	/**
	 * Set value of CreationDateTime
	 * @param context
	 * @param creationdatetime
	 */
	public final void setCreationDateTime(IContext context, java.util.Date creationdatetime)
	{
		getMendixObject().setValue(context, MemberNames.CreationDateTime.toString(), creationdatetime);
	}

	/**
	 * @return value of ObjectCount
	 */
	public final Integer getObjectCount()
	{
		return getObjectCount(getContext());
	}

	/**
	 * @param context
	 * @return value of ObjectCount
	 */
	public final Integer getObjectCount(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.ObjectCount.toString());
	}

	/**
	 * Set value of ObjectCount
	 * @param objectcount
	 */
	public final void setObjectCount(Integer objectcount)
	{
		setObjectCount(getContext(), objectcount);
	}

	/**
	 * Set value of ObjectCount
	 * @param context
	 * @param objectcount
	 */
	public final void setObjectCount(IContext context, Integer objectcount)
	{
		getMendixObject().setValue(context, MemberNames.ObjectCount.toString(), objectcount);
	}

	/**
	 * @return value of ReferencedObjectCount
	 */
	public final Integer getReferencedObjectCount()
	{
		return getReferencedObjectCount(getContext());
	}

	/**
	 * @param context
	 * @return value of ReferencedObjectCount
	 */
	public final Integer getReferencedObjectCount(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.ReferencedObjectCount.toString());
	}

	/**
	 * Set value of ReferencedObjectCount
	 * @param referencedobjectcount
	 */
	public final void setReferencedObjectCount(Integer referencedobjectcount)
	{
		setReferencedObjectCount(getContext(), referencedobjectcount);
	}

	/**
	 * Set value of ReferencedObjectCount
	 * @param context
	 * @param referencedobjectcount
	 */
	public final void setReferencedObjectCount(IContext context, Integer referencedobjectcount)
	{
		getMendixObject().setValue(context, MemberNames.ReferencedObjectCount.toString(), referencedobjectcount);
	}

	/**
	 * @return value of FileDocumentCount
	 */
	public final Integer getFileDocumentCount()
	{
		return getFileDocumentCount(getContext());
	}

	/**
	 * @param context
	 * @return value of FileDocumentCount
	 */
	public final Integer getFileDocumentCount(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.FileDocumentCount.toString());
	}

	/**
	 * Set value of FileDocumentCount
	 * @param filedocumentcount
	 */
	public final void setFileDocumentCount(Integer filedocumentcount)
	{
		setFileDocumentCount(getContext(), filedocumentcount);
	}

	/**
	 * Set value of FileDocumentCount
	 * @param context
	 * @param filedocumentcount
	 */
	public final void setFileDocumentCount(IContext context, Integer filedocumentcount)
	{
		getMendixObject().setValue(context, MemberNames.FileDocumentCount.toString(), filedocumentcount);
	}

	/**
	 * @return value of Checksum
	 */
	public final Long getChecksum()
	{
		return getChecksum(getContext());
	}

	/**
	 * @param context
	 * @return value of Checksum
	 */
	public final Long getChecksum(IContext context)
	{
		return (Long) getMendixObject().getValue(context, MemberNames.Checksum.toString());
	}

	/**
	 * Set value of Checksum
	 * @param checksum
	 */
	public final void setChecksum(Long checksum)
	{
		setChecksum(getContext(), checksum);
	}

	/**
	 * Set value of Checksum
	 * @param context
	 * @param checksum
	 */
	public final void setChecksum(IContext context, Long checksum)
	{
		getMendixObject().setValue(context, MemberNames.Checksum.toString(), checksum);
	}

	/**
	 * @return value of GroupCode
	 */
	public final String getGroupCode()
	{
		return getGroupCode(getContext());
	}

	/**
	 * @param context
	 * @return value of GroupCode
	 */
	public final String getGroupCode(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.GroupCode.toString());
	}

	/**
	 * Set value of GroupCode
	 * @param groupcode
	 */
	public final void setGroupCode(String groupcode)
	{
		setGroupCode(getContext(), groupcode);
	}

	/**
	 * Set value of GroupCode
	 * @param context
	 * @param groupcode
	 */
	public final void setGroupCode(IContext context, String groupcode)
	{
		getMendixObject().setValue(context, MemberNames.GroupCode.toString(), groupcode);
	}

	/**
	 * @return value of Description
	 */
	public final String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final String getDescription(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(IContext context, String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Imported
	 */
	public final Boolean getImported()
	{
		return getImported(getContext());
	}

	/**
	 * @param context
	 * @return value of Imported
	 */
	public final Boolean getImported(IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.Imported.toString());
	}

	/**
	 * Set value of Imported
	 * @param imported
	 */
	public final void setImported(Boolean imported)
	{
		setImported(getContext(), imported);
	}

	/**
	 * Set value of Imported
	 * @param context
	 * @param imported
	 */
	public final void setImported(IContext context, Boolean imported)
	{
		getMendixObject().setValue(context, MemberNames.Imported.toString(), imported);
	}

	/**
	 * @return value of Backup_BackupConfiguration
	 */
	public final objectbackuprestore.proxies.BackupConfiguration getBackup_BackupConfiguration() throws CoreException
	{
		return getBackup_BackupConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of Backup_BackupConfiguration
	 */
	public final objectbackuprestore.proxies.BackupConfiguration getBackup_BackupConfiguration(IContext context) throws CoreException
	{
		objectbackuprestore.proxies.BackupConfiguration result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Backup_BackupConfiguration.toString());
		if (identifier != null)
			result = objectbackuprestore.proxies.BackupConfiguration.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Backup_BackupConfiguration
	 * @param backup_backupconfiguration
	 */
	public final void setBackup_BackupConfiguration(objectbackuprestore.proxies.BackupConfiguration backup_backupconfiguration)
	{
		setBackup_BackupConfiguration(getContext(), backup_backupconfiguration);
	}

	/**
	 * Set value of Backup_BackupConfiguration
	 * @param context
	 * @param backup_backupconfiguration
	 */
	public final void setBackup_BackupConfiguration(IContext context, objectbackuprestore.proxies.BackupConfiguration backup_backupconfiguration)
	{
		if (backup_backupconfiguration == null)
			getMendixObject().setValue(context, MemberNames.Backup_BackupConfiguration.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Backup_BackupConfiguration.toString(), backup_backupconfiguration.getMendixObject().getId());
	}

	/**
	 * @return value of Backup_BackupGroup
	 */
	public final objectbackuprestore.proxies.BackupGroup getBackup_BackupGroup() throws CoreException
	{
		return getBackup_BackupGroup(getContext());
	}

	/**
	 * @param context
	 * @return value of Backup_BackupGroup
	 */
	public final objectbackuprestore.proxies.BackupGroup getBackup_BackupGroup(IContext context) throws CoreException
	{
		objectbackuprestore.proxies.BackupGroup result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Backup_BackupGroup.toString());
		if (identifier != null)
			result = objectbackuprestore.proxies.BackupGroup.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Backup_BackupGroup
	 * @param backup_backupgroup
	 */
	public final void setBackup_BackupGroup(objectbackuprestore.proxies.BackupGroup backup_backupgroup)
	{
		setBackup_BackupGroup(getContext(), backup_backupgroup);
	}

	/**
	 * Set value of Backup_BackupGroup
	 * @param context
	 * @param backup_backupgroup
	 */
	public final void setBackup_BackupGroup(IContext context, objectbackuprestore.proxies.BackupGroup backup_backupgroup)
	{
		if (backup_backupgroup == null)
			getMendixObject().setValue(context, MemberNames.Backup_BackupGroup.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Backup_BackupGroup.toString(), backup_backupgroup.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final objectbackuprestore.proxies.Backup that = (objectbackuprestore.proxies.Backup) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "ObjectBackupRestore.Backup";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
