// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package objectbackuprestore.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class BackupConfigurationTreeData extends objectbackuprestore.proxies.TreeViewWidgetData
{
	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "ObjectBackupRestore.BackupConfigurationTreeData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SelectionType("SelectionType"),
		Action("Action"),
		NewSelectionKey("NewSelectionKey"),
		BackupConfigurationTreeNodeToDisplay("ObjectBackupRestore.BackupConfigurationTreeNodeToDisplay"),
		BackupConfigurationTreeData_BackupConfiguration("ObjectBackupRestore.BackupConfigurationTreeData_BackupConfiguration");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public BackupConfigurationTreeData(IContext context)
	{
		this(context, Core.instantiate(context, "ObjectBackupRestore.BackupConfigurationTreeData"));
	}

	protected BackupConfigurationTreeData(IContext context, IMendixObject backupConfigurationTreeDataMendixObject)
	{
		super(context, backupConfigurationTreeDataMendixObject);
		if (!Core.isSubClassOf("ObjectBackupRestore.BackupConfigurationTreeData", backupConfigurationTreeDataMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a ObjectBackupRestore.BackupConfigurationTreeData");
	}

	/**
	 * @deprecated Use 'new BackupConfigurationTreeData(Context)' instead. Note that the constructor will not insert the new object in the database.
	 */
	@Deprecated
	public static objectbackuprestore.proxies.BackupConfigurationTreeData create(IContext context) throws CoreException
	{
		IMendixObject mendixObject = Core.create(context, "ObjectBackupRestore.BackupConfigurationTreeData");
		return new objectbackuprestore.proxies.BackupConfigurationTreeData(context, mendixObject);
	}

	/**
	 * @deprecated Use 'BackupConfigurationTreeData.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static objectbackuprestore.proxies.BackupConfigurationTreeData initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return objectbackuprestore.proxies.BackupConfigurationTreeData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static objectbackuprestore.proxies.BackupConfigurationTreeData initialize(IContext context, IMendixObject mendixObject)
	{
		return new objectbackuprestore.proxies.BackupConfigurationTreeData(context, mendixObject);
	}

	public static objectbackuprestore.proxies.BackupConfigurationTreeData load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return objectbackuprestore.proxies.BackupConfigurationTreeData.initialize(context, mendixObject);
	}

	/**
	 * Set value of SelectionType
	 * @param selectiontype
	 */
	public final objectbackuprestore.proxies.BackupConfigurationTreeSelectionType getSelectionType()
	{
		return getSelectionType(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectionType
	 */
	public final objectbackuprestore.proxies.BackupConfigurationTreeSelectionType getSelectionType(IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SelectionType.toString());
		if (obj == null)
			return null;

		return objectbackuprestore.proxies.BackupConfigurationTreeSelectionType.valueOf((String) obj);
	}

	/**
	 * Set value of SelectionType
	 * @param selectiontype
	 */
	public final void setSelectionType(objectbackuprestore.proxies.BackupConfigurationTreeSelectionType selectiontype)
	{
		setSelectionType(getContext(), selectiontype);
	}

	/**
	 * Set value of SelectionType
	 * @param context
	 * @param selectiontype
	 */
	public final void setSelectionType(IContext context, objectbackuprestore.proxies.BackupConfigurationTreeSelectionType selectiontype)
	{
		if (selectiontype != null)
			getMendixObject().setValue(context, MemberNames.SelectionType.toString(), selectiontype.toString());
		else
			getMendixObject().setValue(context, MemberNames.SelectionType.toString(), null);
	}

	/**
	 * @return value of BackupConfigurationTreeNodeToDisplay
	 */
	public final objectbackuprestore.proxies.BackupConfigurationTreeNodeData getBackupConfigurationTreeNodeToDisplay() throws CoreException
	{
		return getBackupConfigurationTreeNodeToDisplay(getContext());
	}

	/**
	 * @param context
	 * @return value of BackupConfigurationTreeNodeToDisplay
	 */
	public final objectbackuprestore.proxies.BackupConfigurationTreeNodeData getBackupConfigurationTreeNodeToDisplay(IContext context) throws CoreException
	{
		objectbackuprestore.proxies.BackupConfigurationTreeNodeData result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BackupConfigurationTreeNodeToDisplay.toString());
		if (identifier != null)
			result = objectbackuprestore.proxies.BackupConfigurationTreeNodeData.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BackupConfigurationTreeNodeToDisplay
	 * @param backupconfigurationtreenodetodisplay
	 */
	public final void setBackupConfigurationTreeNodeToDisplay(objectbackuprestore.proxies.BackupConfigurationTreeNodeData backupconfigurationtreenodetodisplay)
	{
		setBackupConfigurationTreeNodeToDisplay(getContext(), backupconfigurationtreenodetodisplay);
	}

	/**
	 * Set value of BackupConfigurationTreeNodeToDisplay
	 * @param context
	 * @param backupconfigurationtreenodetodisplay
	 */
	public final void setBackupConfigurationTreeNodeToDisplay(IContext context, objectbackuprestore.proxies.BackupConfigurationTreeNodeData backupconfigurationtreenodetodisplay)
	{
		if (backupconfigurationtreenodetodisplay == null)
			getMendixObject().setValue(context, MemberNames.BackupConfigurationTreeNodeToDisplay.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BackupConfigurationTreeNodeToDisplay.toString(), backupconfigurationtreenodetodisplay.getMendixObject().getId());
	}

	/**
	 * @return value of BackupConfigurationTreeData_BackupConfiguration
	 */
	public final objectbackuprestore.proxies.BackupConfiguration getBackupConfigurationTreeData_BackupConfiguration() throws CoreException
	{
		return getBackupConfigurationTreeData_BackupConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of BackupConfigurationTreeData_BackupConfiguration
	 */
	public final objectbackuprestore.proxies.BackupConfiguration getBackupConfigurationTreeData_BackupConfiguration(IContext context) throws CoreException
	{
		objectbackuprestore.proxies.BackupConfiguration result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BackupConfigurationTreeData_BackupConfiguration.toString());
		if (identifier != null)
			result = objectbackuprestore.proxies.BackupConfiguration.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BackupConfigurationTreeData_BackupConfiguration
	 * @param backupconfigurationtreedata_backupconfiguration
	 */
	public final void setBackupConfigurationTreeData_BackupConfiguration(objectbackuprestore.proxies.BackupConfiguration backupconfigurationtreedata_backupconfiguration)
	{
		setBackupConfigurationTreeData_BackupConfiguration(getContext(), backupconfigurationtreedata_backupconfiguration);
	}

	/**
	 * Set value of BackupConfigurationTreeData_BackupConfiguration
	 * @param context
	 * @param backupconfigurationtreedata_backupconfiguration
	 */
	public final void setBackupConfigurationTreeData_BackupConfiguration(IContext context, objectbackuprestore.proxies.BackupConfiguration backupconfigurationtreedata_backupconfiguration)
	{
		if (backupconfigurationtreedata_backupconfiguration == null)
			getMendixObject().setValue(context, MemberNames.BackupConfigurationTreeData_BackupConfiguration.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BackupConfigurationTreeData_BackupConfiguration.toString(), backupconfigurationtreedata_backupconfiguration.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final objectbackuprestore.proxies.BackupConfigurationTreeData that = (objectbackuprestore.proxies.BackupConfigurationTreeData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "ObjectBackupRestore.BackupConfigurationTreeData";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
