// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package objectbackuprestore.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class BackupConfiguration
{
	private final IMendixObject backupConfigurationMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "ObjectBackupRestore.BackupConfiguration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Description("Description"),
		XPathConstraint("XPathConstraint"),
		BackupConfiguration_BackupGroup("ObjectBackupRestore.BackupConfiguration_BackupGroup"),
		BackupConfiguration_MxObjectType("ObjectBackupRestore.BackupConfiguration_MxObjectType");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public BackupConfiguration(IContext context)
	{
		this(context, Core.instantiate(context, "ObjectBackupRestore.BackupConfiguration"));
	}

	protected BackupConfiguration(IContext context, IMendixObject backupConfigurationMendixObject)
	{
		if (backupConfigurationMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("ObjectBackupRestore.BackupConfiguration", backupConfigurationMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a ObjectBackupRestore.BackupConfiguration");

		this.backupConfigurationMendixObject = backupConfigurationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'new BackupConfiguration(Context)' instead. Note that the constructor will not insert the new object in the database.
	 */
	@Deprecated
	public static objectbackuprestore.proxies.BackupConfiguration create(IContext context) throws CoreException
	{
		IMendixObject mendixObject = Core.create(context, "ObjectBackupRestore.BackupConfiguration");
		return new objectbackuprestore.proxies.BackupConfiguration(context, mendixObject);
	}

	/**
	 * @deprecated Use 'BackupConfiguration.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static objectbackuprestore.proxies.BackupConfiguration initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return objectbackuprestore.proxies.BackupConfiguration.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static objectbackuprestore.proxies.BackupConfiguration initialize(IContext context, IMendixObject mendixObject)
	{
		return new objectbackuprestore.proxies.BackupConfiguration(context, mendixObject);
	}

	public static objectbackuprestore.proxies.BackupConfiguration load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return objectbackuprestore.proxies.BackupConfiguration.initialize(context, mendixObject);
	}

	public static java.util.List<objectbackuprestore.proxies.BackupConfiguration> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<objectbackuprestore.proxies.BackupConfiguration> result = new java.util.ArrayList<objectbackuprestore.proxies.BackupConfiguration>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//ObjectBackupRestore.BackupConfiguration" + xpathConstraint))
			result.add(objectbackuprestore.proxies.BackupConfiguration.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final String getName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(IContext context, String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Description
	 */
	public final String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final String getDescription(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(IContext context, String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of XPathConstraint
	 */
	public final String getXPathConstraint()
	{
		return getXPathConstraint(getContext());
	}

	/**
	 * @param context
	 * @return value of XPathConstraint
	 */
	public final String getXPathConstraint(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.XPathConstraint.toString());
	}

	/**
	 * Set value of XPathConstraint
	 * @param xpathconstraint
	 */
	public final void setXPathConstraint(String xpathconstraint)
	{
		setXPathConstraint(getContext(), xpathconstraint);
	}

	/**
	 * Set value of XPathConstraint
	 * @param context
	 * @param xpathconstraint
	 */
	public final void setXPathConstraint(IContext context, String xpathconstraint)
	{
		getMendixObject().setValue(context, MemberNames.XPathConstraint.toString(), xpathconstraint);
	}

	/**
	 * @return value of BackupConfiguration_BackupGroup
	 */
	public final objectbackuprestore.proxies.BackupGroup getBackupConfiguration_BackupGroup() throws CoreException
	{
		return getBackupConfiguration_BackupGroup(getContext());
	}

	/**
	 * @param context
	 * @return value of BackupConfiguration_BackupGroup
	 */
	public final objectbackuprestore.proxies.BackupGroup getBackupConfiguration_BackupGroup(IContext context) throws CoreException
	{
		objectbackuprestore.proxies.BackupGroup result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BackupConfiguration_BackupGroup.toString());
		if (identifier != null)
			result = objectbackuprestore.proxies.BackupGroup.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BackupConfiguration_BackupGroup
	 * @param backupconfiguration_backupgroup
	 */
	public final void setBackupConfiguration_BackupGroup(objectbackuprestore.proxies.BackupGroup backupconfiguration_backupgroup)
	{
		setBackupConfiguration_BackupGroup(getContext(), backupconfiguration_backupgroup);
	}

	/**
	 * Set value of BackupConfiguration_BackupGroup
	 * @param context
	 * @param backupconfiguration_backupgroup
	 */
	public final void setBackupConfiguration_BackupGroup(IContext context, objectbackuprestore.proxies.BackupGroup backupconfiguration_backupgroup)
	{
		if (backupconfiguration_backupgroup == null)
			getMendixObject().setValue(context, MemberNames.BackupConfiguration_BackupGroup.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BackupConfiguration_BackupGroup.toString(), backupconfiguration_backupgroup.getMendixObject().getId());
	}

	/**
	 * @return value of BackupConfiguration_MxObjectType
	 */
	public final mxmodelreflection.proxies.MxObjectType getBackupConfiguration_MxObjectType() throws CoreException
	{
		return getBackupConfiguration_MxObjectType(getContext());
	}

	/**
	 * @param context
	 * @return value of BackupConfiguration_MxObjectType
	 */
	public final mxmodelreflection.proxies.MxObjectType getBackupConfiguration_MxObjectType(IContext context) throws CoreException
	{
		mxmodelreflection.proxies.MxObjectType result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BackupConfiguration_MxObjectType.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectType.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BackupConfiguration_MxObjectType
	 * @param backupconfiguration_mxobjecttype
	 */
	public final void setBackupConfiguration_MxObjectType(mxmodelreflection.proxies.MxObjectType backupconfiguration_mxobjecttype)
	{
		setBackupConfiguration_MxObjectType(getContext(), backupconfiguration_mxobjecttype);
	}

	/**
	 * Set value of BackupConfiguration_MxObjectType
	 * @param context
	 * @param backupconfiguration_mxobjecttype
	 */
	public final void setBackupConfiguration_MxObjectType(IContext context, mxmodelreflection.proxies.MxObjectType backupconfiguration_mxobjecttype)
	{
		if (backupconfiguration_mxobjecttype == null)
			getMendixObject().setValue(context, MemberNames.BackupConfiguration_MxObjectType.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BackupConfiguration_MxObjectType.toString(), backupconfiguration_mxobjecttype.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return backupConfigurationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final objectbackuprestore.proxies.BackupConfiguration that = (objectbackuprestore.proxies.BackupConfiguration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "ObjectBackupRestore.BackupConfiguration";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
