// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package objectbackuprestore.proxies;

public enum IncludeInBackup
{
	Yes(new String[][] { new String[] { "en_US", "Yes" }, new String[] { "nl_NL", "Ja" } }),
	No(new String[][] { new String[] { "en_US", "No" }, new String[] { "nl_NL", "Nee" } }),
	Unknown(new String[][] { new String[] { "en_US", "Unknown" }, new String[] { "nl_NL", "Onbekend" } });

	private java.util.Map<String,String> captions;

	private IncludeInBackup(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
