// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package objectbackuprestore.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class TempRestoredObjectAttribute
{
	private final IMendixObject tempRestoredObjectAttributeMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "ObjectBackupRestore.TempRestoredObjectAttribute";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AttributeName("AttributeName"),
		AttributeValue("AttributeValue"),
		TempRestoredObjectAttribute_TempRestoredObject("ObjectBackupRestore.TempRestoredObjectAttribute_TempRestoredObject");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public TempRestoredObjectAttribute(IContext context)
	{
		this(context, Core.instantiate(context, "ObjectBackupRestore.TempRestoredObjectAttribute"));
	}

	protected TempRestoredObjectAttribute(IContext context, IMendixObject tempRestoredObjectAttributeMendixObject)
	{
		if (tempRestoredObjectAttributeMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("ObjectBackupRestore.TempRestoredObjectAttribute", tempRestoredObjectAttributeMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a ObjectBackupRestore.TempRestoredObjectAttribute");

		this.tempRestoredObjectAttributeMendixObject = tempRestoredObjectAttributeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'new TempRestoredObjectAttribute(Context)' instead. Note that the constructor will not insert the new object in the database.
	 */
	@Deprecated
	public static objectbackuprestore.proxies.TempRestoredObjectAttribute create(IContext context) throws CoreException
	{
		IMendixObject mendixObject = Core.create(context, "ObjectBackupRestore.TempRestoredObjectAttribute");
		return new objectbackuprestore.proxies.TempRestoredObjectAttribute(context, mendixObject);
	}

	/**
	 * @deprecated Use 'TempRestoredObjectAttribute.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static objectbackuprestore.proxies.TempRestoredObjectAttribute initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return objectbackuprestore.proxies.TempRestoredObjectAttribute.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static objectbackuprestore.proxies.TempRestoredObjectAttribute initialize(IContext context, IMendixObject mendixObject)
	{
		return new objectbackuprestore.proxies.TempRestoredObjectAttribute(context, mendixObject);
	}

	public static objectbackuprestore.proxies.TempRestoredObjectAttribute load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return objectbackuprestore.proxies.TempRestoredObjectAttribute.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of AttributeName
	 */
	public final String getAttributeName()
	{
		return getAttributeName(getContext());
	}

	/**
	 * @param context
	 * @return value of AttributeName
	 */
	public final String getAttributeName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.AttributeName.toString());
	}

	/**
	 * Set value of AttributeName
	 * @param attributename
	 */
	public final void setAttributeName(String attributename)
	{
		setAttributeName(getContext(), attributename);
	}

	/**
	 * Set value of AttributeName
	 * @param context
	 * @param attributename
	 */
	public final void setAttributeName(IContext context, String attributename)
	{
		getMendixObject().setValue(context, MemberNames.AttributeName.toString(), attributename);
	}

	/**
	 * @return value of AttributeValue
	 */
	public final String getAttributeValue()
	{
		return getAttributeValue(getContext());
	}

	/**
	 * @param context
	 * @return value of AttributeValue
	 */
	public final String getAttributeValue(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.AttributeValue.toString());
	}

	/**
	 * Set value of AttributeValue
	 * @param attributevalue
	 */
	public final void setAttributeValue(String attributevalue)
	{
		setAttributeValue(getContext(), attributevalue);
	}

	/**
	 * Set value of AttributeValue
	 * @param context
	 * @param attributevalue
	 */
	public final void setAttributeValue(IContext context, String attributevalue)
	{
		getMendixObject().setValue(context, MemberNames.AttributeValue.toString(), attributevalue);
	}

	/**
	 * @return value of TempRestoredObjectAttribute_TempRestoredObject
	 */
	public final objectbackuprestore.proxies.TempRestoredObject getTempRestoredObjectAttribute_TempRestoredObject() throws CoreException
	{
		return getTempRestoredObjectAttribute_TempRestoredObject(getContext());
	}

	/**
	 * @param context
	 * @return value of TempRestoredObjectAttribute_TempRestoredObject
	 */
	public final objectbackuprestore.proxies.TempRestoredObject getTempRestoredObjectAttribute_TempRestoredObject(IContext context) throws CoreException
	{
		objectbackuprestore.proxies.TempRestoredObject result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TempRestoredObjectAttribute_TempRestoredObject.toString());
		if (identifier != null)
			result = objectbackuprestore.proxies.TempRestoredObject.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TempRestoredObjectAttribute_TempRestoredObject
	 * @param temprestoredobjectattribute_temprestoredobject
	 */
	public final void setTempRestoredObjectAttribute_TempRestoredObject(objectbackuprestore.proxies.TempRestoredObject temprestoredobjectattribute_temprestoredobject)
	{
		setTempRestoredObjectAttribute_TempRestoredObject(getContext(), temprestoredobjectattribute_temprestoredobject);
	}

	/**
	 * Set value of TempRestoredObjectAttribute_TempRestoredObject
	 * @param context
	 * @param temprestoredobjectattribute_temprestoredobject
	 */
	public final void setTempRestoredObjectAttribute_TempRestoredObject(IContext context, objectbackuprestore.proxies.TempRestoredObject temprestoredobjectattribute_temprestoredobject)
	{
		if (temprestoredobjectattribute_temprestoredobject == null)
			getMendixObject().setValue(context, MemberNames.TempRestoredObjectAttribute_TempRestoredObject.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TempRestoredObjectAttribute_TempRestoredObject.toString(), temprestoredobjectattribute_temprestoredobject.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return tempRestoredObjectAttributeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final objectbackuprestore.proxies.TempRestoredObjectAttribute that = (objectbackuprestore.proxies.TempRestoredObjectAttribute) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "ObjectBackupRestore.TempRestoredObjectAttribute";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
