// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package objectbackuprestore.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the ObjectBackupRestore module

	public static String getOBJECT_BACKUP_RESTORE_LOG_NODE()
	{
		return (String)Core.getConfiguration().getConstantValue("ObjectBackupRestore.OBJECT_BACKUP_RESTORE_LOG_NODE");
	}
}